packages:
  - packages/*
  - tools/*
linkWorkspacePackages: true
allowBuilds:
  "@google/genai": true
  deno: false
  esbuild: true
  protobufjs: true
  tesseract.js: true
  tree-sitter-bash: false
  zeromq: false
