import type { BibleTranslationAbbreviation } from "./bible-translations.js";

/** One self-contained Bible passage selected for the working-message rotation. */
export type BibleVerseMessage = {
  id: string;
  text: string;
  reference: string;
  translation: BibleTranslationAbbreviation;
  verseCount: number;
  book: string;
};

/** Offline Bible readings, with one editorially selected translation per passage. */
export const bibleVerseMessages = [
  // Pentateuch and Old Testament history
  {
    id: "genesis-1-1",
    text: "In the beginning God created the heavens and the earth.",
    reference: "Genesis 1:1",
    translation: "BSB",
    verseCount: 1,
    book: "Genesis",
  },
  {
    id: "genesis-1-26",
    text: "Then God said, “Let Us make man in Our image, after Our likeness, to rule over the fish of the sea and the birds of the air, over the livestock, and over all the earth itself and every creature that crawls upon it.”",
    reference: "Genesis 1:26",
    translation: "BSB",
    verseCount: 1,
    book: "Genesis",
  },
  {
    id: "genesis-2-2-3",
    text: "When on the seventh day God finished the work which he had done, he rested that day from all his work. God blessed the seventh day and set it apart, for in it he rested from all the creative work which he had done.",
    reference: "Genesis 2:2-3",
    translation: "OEB",
    verseCount: 2,
    book: "Genesis",
  },
  {
    id: "genesis-12-1-2",
    text: "Then the LORD said to Abram, “Leave your country, your kindred, and your father’s household, and go to the land I will show you. I will make you into a great nation, and I will bless you; I will make your name great, so that you will be a blessing.",
    reference: "Genesis 12:1-2",
    translation: "BSB",
    verseCount: 2,
    book: "Genesis",
  },
  {
    id: "genesis-15-5-6",
    text: "Then God brought him outside and said, “Look now toward heaven and count the stars, if you are able to count them! So will your descendants be.” Abram believed in the Lord; and the Lord reckoned it to him as righteousness,",
    reference: "Genesis 15:5-6",
    translation: "OEB",
    verseCount: 2,
    book: "Genesis",
  },
  {
    id: "genesis-18-19",
    text: "For I have chosen him, so that he will command his children and his household after him to keep the way of the LORD by doing what is right and just, in order that the LORD may bring upon Abraham what He has promised.”",
    reference: "Genesis 18:19",
    translation: "BSB",
    verseCount: 1,
    book: "Genesis",
  },
  {
    id: "genesis-21-1-2",
    text: "The LORD visited Sarah as he had said, and the LORD did to Sarah as he had spoken. Sarah conceived, and bore Abraham a son in his old age, at the set time of which God had spoken to him.",
    reference: "Genesis 21:1-2",
    translation: "WEB",
    verseCount: 2,
    book: "Genesis",
  },
  {
    id: "genesis-22-14",
    text: "And Abraham called the name of that place Jehovah-jireh: as it is said to this day, In the mount of Jehovah it shall be provided.",
    reference: "Genesis 22:14",
    translation: "ASV",
    verseCount: 1,
    book: "Genesis",
  },
  {
    id: "genesis-33-4",
    text: "Esau ran to meet him, threw his arms about his neck, and kissed him, and they wept.",
    reference: "Genesis 33:4",
    translation: "OEB",
    verseCount: 1,
    book: "Genesis",
  },
  {
    id: "genesis-50-19-20",
    text: "But Joseph said to them, “Do not be afraid; for am I in the place of God? You plotted mischief against me, but God intended it for good, in order to accomplish what is now being done, the saving of the lives of many people.",
    reference: "Genesis 50:19-20",
    translation: "OEB",
    verseCount: 2,
    book: "Genesis",
  },
  {
    id: "exodus-3-7",
    text: "And Jehovah said, I have seen assuredly the affliction of my people who are in Egypt, and their cry have I heard on account of their taskmasters; for I know their sorrows.",
    reference: "Exodus 3:7",
    translation: "DARBY",
    verseCount: 1,
    book: "Exodus",
  },
  {
    id: "exodus-4-10",
    text: "“Please, Lord,” Moses replied, “I have never been eloquent, neither in the past nor since You have spoken to Your servant, for I am slow of speech and tongue.”",
    reference: "Exodus 4:10",
    translation: "BSB",
    verseCount: 1,
    book: "Exodus",
  },
  {
    id: "exodus-14-13-14",
    text: "But Moses told the people, “Do not be afraid. Stand firm and you will see the LORD’s salvation, which He will accomplish for you today; for the Egyptians you see today, you will never see again. The LORD will fight for you; you need only to be still.”",
    reference: "Exodus 14:13-14",
    translation: "BSB",
    verseCount: 2,
    book: "Exodus",
  },
  {
    id: "exodus-18-17-18",
    text: "But Moses’ father-in-law said to him, “What you are doing is not good. Surely you and these people with you will wear yourselves out, because the task is too heavy for you. You cannot handle it alone.",
    reference: "Exodus 18:17-18",
    translation: "BSB",
    verseCount: 2,
    book: "Exodus",
  },
  {
    id: "exodus-23-4-5",
    text: "If you encounter your enemy’s stray ox or donkey, you must return it to him. If you see the donkey of one who hates you fallen under its load, do not leave it there; you must help him with it.",
    reference: "Exodus 23:4-5",
    translation: "BSB",
    verseCount: 2,
    book: "Exodus",
  },
  {
    id: "exodus-33-14",
    text: "He said, “My presence will go with you, and I will give you rest.”",
    reference: "Exodus 33:14",
    translation: "WEB",
    verseCount: 1,
    book: "Exodus",
  },
  {
    id: "leviticus-19-9",
    text: "When you reap the harvest of your land, you are not to reap to the very edges of your field or gather the gleanings of your harvest.",
    reference: "Leviticus 19:9",
    translation: "BSB",
    verseCount: 1,
    book: "Leviticus",
  },
  {
    id: "leviticus-19-17",
    text: "Thou shalt not hate thy brother in thy heart; thou shalt earnestly rebuke thy neighbour, lest thou bear sin on account of him.",
    reference: "Leviticus 19:17",
    translation: "DARBY",
    verseCount: 1,
    book: "Leviticus",
  },
  {
    id: "leviticus-25-35",
    text: "And if thy brother be waxed poor, and his hand fail with thee; then thou shalt uphold him: as a stranger and a sojourner shall he live with thee.",
    reference: "Leviticus 25:35",
    translation: "ASV",
    verseCount: 1,
    book: "Leviticus",
  },
  {
    id: "numbers-6-24-26",
    text: "Jehovah bless thee, and keep thee; Jehovah make his face shine upon thee, and be gracious unto thee; Jehovah lift up his countenance upon thee, and give thee peace.",
    reference: "Numbers 6:24-26",
    translation: "DARBY",
    verseCount: 3,
    book: "Numbers",
  },
  {
    id: "numbers-11-11",
    text: "And he said to the Lord: Why hast thou afflicted thy servant? wherefore do I not find favour before thee? and why hast thou laid the weight of all this people upon me?",
    reference: "Numbers 11:11",
    translation: "DRA",
    verseCount: 1,
    book: "Numbers",
  },
  {
    id: "joshua-24-14",
    text: "So revere the Lord and serve him honestly and loyally, put away the gods your ancestors served on the east of the Euphrates and in Egypt, and serve the Lord yourselves.",
    reference: "Joshua 24:14",
    translation: "OEB",
    verseCount: 1,
    book: "Joshua",
  },
  {
    id: "judges-6-12",
    text: "And the angel of Jehovah appeared unto him, and said unto him, Jehovah is with thee, thou mighty man of valor.",
    reference: "Judges 6:12",
    translation: "ASV",
    verseCount: 1,
    book: "Judges",
  },
  {
    id: "judges-10-15-16",
    text: "“We have sinned,” the Israelites said to the LORD. “Deal with us as You see fit; but please deliver us today!” So they put away the foreign gods from among them and served the LORD, and He could no longer bear the misery of Israel.",
    reference: "Judges 10:15-16",
    translation: "BSB",
    verseCount: 2,
    book: "Judges",
  },
  {
    id: "ruth-1-16",
    text: "But Ruth answered, “Do not urge me to leave you or to go back. I will go where you go, and I will stay wherever you stay. Your people will be my people, and your God my God;",
    reference: "Ruth 1:16",
    translation: "OEB",
    verseCount: 1,
    book: "Ruth",
  },
  {
    id: "ruth-2-11",
    text: "Boaz replied, “I have heard what you have done for your mother-in-law since the death of your husband, and how you left your father and mother and your native land to come to a people that you did not know before.",
    reference: "Ruth 2:11",
    translation: "OEB",
    verseCount: 1,
    book: "Ruth",
  },
  {
    id: "ruth-2-20",
    text: "Then Naomi said to her daughter-in-law, “May he be blessed by the LORD, who has not withdrawn His kindness from the living or the dead.” Naomi continued, “The man is a close relative. He is one of our kinsman-redeemers.”",
    reference: "Ruth 2:20",
    translation: "BSB",
    verseCount: 1,
    book: "Ruth",
  },
  {
    id: "1-samuel-2-1",
    text: "And Hannah prayed, and said: My heart exulteth in Jehovah; My horn is exalted in Jehovah; My mouth is enlarged over mine enemies; Because I rejoice in thy salvation.",
    reference: "1 Samuel 2:1",
    translation: "ASV",
    verseCount: 1,
    book: "1 Samuel",
  },
  {
    id: "1-samuel-3-9",
    text: "“Go and lie down,” he said to Samuel, “and if He calls you, say, ‘Speak, LORD, for Your servant is listening.’” So Samuel went and lay down in his place.",
    reference: "1 Samuel 3:9",
    translation: "BSB",
    verseCount: 1,
    book: "1 Samuel",
  },
  {
    id: "1-samuel-12-20",
    text: "And Samuel said unto the people, Fear not: ye have indeed done all this evil; yet turn not aside from following Jehovah, but serve Jehovah with all your heart:",
    reference: "1 Samuel 12:20",
    translation: "ASV",
    verseCount: 1,
    book: "1 Samuel",
  },
  {
    id: "1-samuel-16-7",
    text: "But the LORD said to Samuel, “Don’t look on his face, or on the height of his stature, because I have rejected him; for I don’t see as man sees. For man looks at the outward appearance, but the LORD looks at the heart.”",
    reference: "1 Samuel 16:7",
    translation: "WEB",
    verseCount: 1,
    book: "1 Samuel",
  },
  {
    id: "1-samuel-24-5-6",
    text: "Afterward, David’s heart struck him because he had cut off Saul’s skirt. He said to his men, “The LORD forbid that I should do this thing to my lord, the LORD’s anointed, to stretch out my hand against him, since he is the LORD’s anointed.”",
    reference: "1 Samuel 24:5-6",
    translation: "WEB",
    verseCount: 2,
    book: "1 Samuel",
  },
  {
    id: "2-samuel-7-22",
    text: "Wherefore thou art great, Jehovah Elohim; for there is none like thee, neither is there any God beside thee, according to all that we have heard with our ears.",
    reference: "2 Samuel 7:22",
    translation: "DARBY",
    verseCount: 1,
    book: "2 Samuel",
  },
  {
    id: "2-samuel-12-13",
    text: "And David said unto Nathan, I have sinned against Jehovah. And Nathan said unto David, Jehovah also hath put away thy sin; thou shalt not die.",
    reference: "2 Samuel 12:13",
    translation: "ASV",
    verseCount: 1,
    book: "2 Samuel",
  },
  {
    id: "2-samuel-22-31-33",
    text: "As for God, his way is perfect; The word of Jehovah is tried: He is a shield to all that trust in him. For who is God, save Jehovah? And who is a rock, save our God? God is my strong fortress, And he maketh my way perfectly smooth.",
    reference: "2 Samuel 22:31-33",
    translation: "DARBY",
    verseCount: 3,
    book: "2 Samuel",
  },
  {
    id: "1-kings-3-9-10",
    text: "Give your servant therefore an understanding heart to judge your people, that I may discern between good and evil; for who is able to judge this great people of yours?” This request pleased the Lord, that Solomon had asked this thing.",
    reference: "1 Kings 3:9-10",
    translation: "WEB",
    verseCount: 2,
    book: "1 Kings",
  },
  {
    id: "1-kings-19-13",
    text: "When Elijah heard it, he wrapped his face in his cloak and went out and stood at the mouth of the cave. Suddenly a voice came to him and said, “What are you doing here, Elijah?”",
    reference: "1 Kings 19:13",
    translation: "BSB",
    verseCount: 1,
    book: "1 Kings",
  },
  {
    id: "2-kings-5-13",
    text: "And his servants came near, and spake unto him, and said, My father, if the prophet had bid thee do some great thing, wouldest thou not have done it? how much rather then, when he saith to thee, Wash, and be clean?",
    reference: "2 Kings 5:13",
    translation: "ASV",
    verseCount: 1,
    book: "2 Kings",
  },
  {
    id: "1-chronicles-16-8-10",
    text: "O give thanks unto Jehovah, call upon his name; Make known his doings among the peoples. Sing unto him, sing praises unto him; Talk ye of all his marvellous works. Glory ye in his holy name; Let the heart of them rejoice that seek Jehovah.",
    reference: "1 Chronicles 16:8-10",
    translation: "ASV",
    verseCount: 3,
    book: "1 Chronicles",
  },
  {
    id: "1-chronicles-29-11",
    text: "Thine, O Jehovah, is the greatness, and the power, and the glory, and the victory, and the majesty: for all that is in the heavens and in the earth is thine; thine is the kingdom, O Jehovah, and thou art exalted as head above all.",
    reference: "1 Chronicles 29:11",
    translation: "ASV",
    verseCount: 1,
    book: "1 Chronicles",
  },
  {
    id: "2-chronicles-20-12-13",
    text: "Our God, will you not judge them? For we have no might against this great company that comes against us. We don’t know what to do, but our eyes are on you.” All Judah stood before the LORD, with their little ones, their wives, and their children.",
    reference: "2 Chronicles 20:12-13",
    translation: "WEB",
    verseCount: 2,
    book: "2 Chronicles",
  },
  {
    id: "ezra-8-21",
    text: "And I proclaimed a fast there, at the river Ahava, that we might humble ourselves before our God, to seek of him a right way for us, and for our little ones, and for all our substance.",
    reference: "Ezra 8:21",
    translation: "DARBY",
    verseCount: 1,
    book: "Ezra",
  },
  {
    id: "nehemiah-1-7",
    text: "We have behaved corruptly against You and have not kept the commandments, statutes, and ordinances that You gave Your servant Moses.",
    reference: "Nehemiah 1:7",
    translation: "BSB",
    verseCount: 1,
    book: "Nehemiah",
  },
  {
    id: "nehemiah-2-17",
    text: "Then I said to them, “You see the trouble we are in. Jerusalem lies in ruins, and its gates have been burned down. Come, let us rebuild the wall of Jerusalem, so that we will no longer be a disgrace.”",
    reference: "Nehemiah 2:17",
    translation: "BSB",
    verseCount: 1,
    book: "Nehemiah",
  },
  {
    id: "nehemiah-8-9",
    text: "And Nehemiah, who was the governor, and Ezra the priest the scribe, and the Levites that taught the people, said unto all the people, This day is holy unto Jehovah your God; mourn not, nor weep. For all the people wept, when they heard the words of the law.",
    reference: "Nehemiah 8:9",
    translation: "ASV",
    verseCount: 1,
    book: "Nehemiah",
  },
  {
    id: "esther-8-3",
    text: "Then Esther sought another audience with the king and fell at his feet and with tears begged him to avert the evil planned by Haman the Agagite and to frustrate his designs against the Jews.",
    reference: "Esther 8:3",
    translation: "OEB",
    verseCount: 1,
    book: "Esther",
  },
  {
    id: "genesis-24-12-13",
    text: "Then he said, “Lord, God of my master Abraham, give me, I pray, success today, and show kindness to my master Abraham. Here I am standing by the spring of water, and the daughters of the men of the town are coming out to draw water.",
    reference: "Genesis 24:12-13",
    translation: "OEB",
    verseCount: 2,
    book: "Genesis",
  },
  {
    id: "genesis-45-4-5",
    text: "Joseph said to his brothers, “Come near to me, please.” They came near. He said, “I am Joseph, your brother, whom you sold into Egypt. Now don’t be grieved, nor angry with yourselves, that you sold me here, for God sent me before you to preserve life.",
    reference: "Genesis 45:4-5",
    translation: "WEB",
    verseCount: 2,
    book: "Genesis",
  },
  {
    id: "exodus-32-11",
    text: "And Moses besought Jehovah his God, and said, Why, Jehovah, doth thy wrath burn against thy people, which thou hast brought forth out of the land of Egypt with great power and with a strong hand?",
    reference: "Exodus 32:11",
    translation: "DARBY",
    verseCount: 1,
    book: "Exodus",
  },
  {
    id: "leviticus-25-10",
    text: "And ye shall hallow the fiftieth year, and proclaim liberty throughout the land unto all the inhabitants thereof: it shall be a jubilee unto you; and ye shall return every man unto his possession, and ye shall return every man unto his family.",
    reference: "Leviticus 25:10",
    translation: "ASV",
    verseCount: 1,
    book: "Leviticus",
  },
  {
    id: "deuteronomy-6-4-5",
    text: "Hear, O Israel, the Lord our God is one Lord. Thou shalt love the Lord thy God with thy whole heart, and with thy whole soul, and with thy whole strength.",
    reference: "Deuteronomy 6:4-5",
    translation: "DRA",
    verseCount: 2,
    book: "Deuteronomy",
  },
  {
    id: "deuteronomy-8-10",
    text: "You shall eat and be full, and you shall bless the LORD your God for the good land which he has given you.",
    reference: "Deuteronomy 8:10",
    translation: "WEB",
    verseCount: 1,
    book: "Deuteronomy",
  },
  {
    id: "deuteronomy-10-17",
    text: "For the LORD your God, he is God of gods and Lord of lords, the great God, the mighty, and the awesome, who doesn’t respect persons or take bribes.",
    reference: "Deuteronomy 10:17",
    translation: "WEB",
    verseCount: 1,
    book: "Deuteronomy",
  },
  {
    id: "deuteronomy-15-9",
    text: "Beware that there be not a base thought in thy heart, saying, The seventh year, the year of release, is at hand; and thine eye be evil against thy poor brother, and thou give him nought; and he cry unto Jehovah against thee, and it be sin unto thee.",
    reference: "Deuteronomy 15:9",
    translation: "ASV",
    verseCount: 1,
    book: "Deuteronomy",
  },
  {
    id: "deuteronomy-16-18",
    text: "Judges and officers shalt thou make thee in all thy gates, which Jehovah thy God giveth thee, throughout thy tribes, that they may judge the people with just judgment.",
    reference: "Deuteronomy 16:18",
    translation: "DARBY",
    verseCount: 1,
    book: "Deuteronomy",
  },
  {
    id: "deuteronomy-24-19",
    text: "When thou reapest thy harvest in thy field, and hast forgot a sheaf in the field, thou shalt not go again to fetch it: it shall be for the sojourner, for the fatherless, and for the widow; that Jehovah thy God may bless thee in all the work of thy hands.",
    reference: "Deuteronomy 24:19",
    translation: "ASV",
    verseCount: 1,
    book: "Deuteronomy",
  },
  {
    id: "deuteronomy-30-11-12",
    text: "For this commandment I give you today is not too difficult for you or beyond your reach. It is not in heaven, that you should need to ask, ‘Who will ascend into heaven to get it for us and proclaim it, that we may obey it?’",
    reference: "Deuteronomy 30:11-12",
    translation: "BSB",
    verseCount: 2,
    book: "Deuteronomy",
  },
  {
    id: "deuteronomy-31-6",
    text: "Be strong and of good courage, fear not, nor be affrighted at them: for Jehovah thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.",
    reference: "Deuteronomy 31:6",
    translation: "ASV",
    verseCount: 1,
    book: "Deuteronomy",
  },
  {
    id: "deuteronomy-32-3-4",
    text: "For I will proclaim the name of Jehovah: Ascribe ye greatness unto our God. The Rock, his work is perfect; For all his ways are justice: A God of faithfulness and without iniquity, Just and right is he.",
    reference: "Deuteronomy 32:3-4",
    translation: "ASV",
    verseCount: 2,
    book: "Deuteronomy",
  },
  {
    id: "1-samuel-30-6",
    text: "And David was greatly afflicted: for the people had a mind to stone him, for the soul of every man was bitterly grieved for his sons, and daughters: but David took courage in the Lord his God.",
    reference: "1 Samuel 30:6",
    translation: "DRA",
    verseCount: 1,
    book: "1 Samuel",
  },

  // Additional Old Testament readings
  {
    id: "job-19-25",
    text: "But as for me I know that my Redeemer liveth, And at last he will stand up upon the earth:",
    reference: "Job 19:25",
    translation: "ASV",
    verseCount: 1,
    book: "Job",
  },
  {
    id: "jeremiah-9-24",
    text: "But let him who boasts boast in this, that he understands and knows Me, that I am the LORD, who exercises loving devotion, justice and righteousness on the earth— for I delight in these things,” declares the LORD.",
    reference: "Jeremiah 9:24",
    translation: "BSB",
    verseCount: 1,
    book: "Jeremiah",
  },
  {
    id: "isaiah-58-7",
    text: "Isn’t it to share your bread with the hungry, to bring the poor and homeless into your home, to clothe the naked when you see him, and not to turn away from your own flesh and blood?",
    reference: "Isaiah 58:7",
    translation: "BSB",
    verseCount: 1,
    book: "Isaiah",
  },
  {
    id: "zephaniah-3-17",
    text: "The Lord your God is in your midst, a victorious hero. He will rejoice over you with joy, he will renew his love, he will exult over you with singing,",
    reference: "Zephaniah 3:17",
    translation: "OEB",
    verseCount: 1,
    book: "Zephaniah",
  },
  {
    id: "psalm-133-1",
    text: "Behold, how good and how pleasant it is For brethren to dwell together in unity!",
    reference: "Psalm 133:1",
    translation: "ASV",
    verseCount: 1,
    book: "Psalm",
  },
  {
    id: "proverbs-16-8",
    text: "Better a little with righteousness than great gain with injustice.",
    reference: "Proverbs 16:8",
    translation: "BSB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "joshua-24-15",
    text: "If you are unwilling to serve the Lord, then choose today whom you will serve, either the gods your ancestors served on the east of the Euphrates or the gods of the Amorites in whose land you are living. But as for me and my house, we will serve the Lord.”",
    reference: "Joshua 24:15",
    translation: "OEB",
    verseCount: 1,
    book: "Joshua",
  },

  // Wisdom, poetry, and the prophets
  {
    id: "job-1-20-21",
    text: "Then Job stood up, tore his robe, and shaved his head. He fell to the ground and worshiped, saying: “Naked I came from my mother’s womb, and naked I will return. The LORD gave, and the LORD has taken away. Blessed be the name of the LORD.”",
    reference: "Job 1:20-21",
    translation: "BSB",
    verseCount: 2,
    book: "Job",
  },
  {
    id: "job-23-10-11",
    text: "Yet He knows the way I have taken; when He has tested me, I will come forth as gold. My feet have followed in His tracks; I have kept His way without turning aside.",
    reference: "Job 23:10-11",
    translation: "BSB",
    verseCount: 2,
    book: "Job",
  },
  {
    id: "job-28-28",
    text: "And unto man he said, Behold, the fear of the Lord, that is wisdom; And to depart from evil is understanding.",
    reference: "Job 28:28",
    translation: "ASV",
    verseCount: 1,
    book: "Job",
  },
  {
    id: "job-31-13-14",
    text: "If I have rejected the cause of my manservant or maidservant when they made a complaint against me, what will I do when God rises to judge? How will I answer when called to account?",
    reference: "Job 31:13-14",
    translation: "BSB",
    verseCount: 2,
    book: "Job",
  },
  {
    id: "job-42-5-6",
    text: "I had heard of thee by the hearing of the ear; But now mine eye seeth thee: Wherefore I abhor myself, And repent in dust and ashes.",
    reference: "Job 42:5-6",
    translation: "ASV",
    verseCount: 2,
    book: "Job",
  },
  {
    id: "psalm-1-1-2",
    text: "Blessed is the man that walketh not in the counsel of the wicked, Nor standeth in the way of sinners, Nor sitteth in the seat of scoffers: But his delight is in the law of Jehovah; And on his law doth he meditate day and night.",
    reference: "Psalm 1:1-2",
    translation: "ASV",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-8-3-4",
    text: "When I behold Your heavens, the work of Your fingers, the moon and the stars, which You have set in place— what is man that You are mindful of him, or the son of man that You care for him?",
    reference: "Psalm 8:3-4",
    translation: "BSB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-13-5-6",
    text: "But I trust in your loving kindness. My heart rejoices in your salvation. I will sing to the LORD, because he has been good to me.",
    reference: "Psalm 13:5-6",
    translation: "WEB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-16-7-8",
    text: "I praise the Lord for his counsel, which so stirs my heart in the night. I keep the Lord always in mind: with him at my hand, I can never be moved.",
    reference: "Psalm 16:7-8",
    translation: "OEB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-19-7-8",
    text: "The Law of the LORD is perfect, reviving the soul; the testimony of the LORD is trustworthy, making wise the simple. The precepts of the LORD are right, bringing joy to the heart; the commandments of the LORD are radiant, giving light to the eyes.",
    reference: "Psalm 19:7-8",
    translation: "BSB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-23-1-3",
    text: "The LORD is my shepherd; I shall lack nothing. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul. He guides me in the paths of righteousness for his name’s sake.",
    reference: "Psalm 23:1-3",
    translation: "WEB",
    verseCount: 3,
    book: "Psalm",
  },
  {
    id: "psalm-27-13-14",
    text: "I had fainted, unless I had believed to see the goodness of Jehovah In the land of the living. Wait for Jehovah: Be strong, and let thy heart take courage; Yea, wait thou for Jehovah.",
    reference: "Psalm 27:13-14",
    translation: "ASV",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-34-4-5",
    text: "I sought the LORD, and He answered me; He delivered me from all my fears. Those who look to Him are radiant with joy; their faces shall never be ashamed.",
    reference: "Psalm 34:4-5",
    translation: "BSB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-40-1-2",
    text: "For the Lord I waited and waited, till, inclining to me, he heard my cry. From the horrible pit he drew me, up out of the miry clay; he set my feet on a rock, and my steps he made firm.",
    reference: "Psalm 40:1-2",
    translation: "OEB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-42-5",
    text: "Why am I downcast? Why this moaning within me? Hope in God; for yet will I praise him, my help, my God.",
    reference: "Psalm 42:5",
    translation: "OEB",
    verseCount: 1,
    book: "Psalm",
  },
  {
    id: "psalm-46-1",
    text: "God is our refuge and strength, a very present help in trouble.",
    reference: "Psalm 46:1",
    translation: "WEB",
    verseCount: 1,
    book: "Psalm",
  },
  {
    id: "psalm-51-10-12",
    text: "Create in me a clean heart, O God; And renew a right spirit within me. Cast me not away from thy presence; And take not thy holy Spirit from me. Restore unto me the joy of thy salvation; And uphold me with a willing spirit.",
    reference: "Psalm 51:10-12",
    translation: "ASV",
    verseCount: 3,
    book: "Psalm",
  },
  {
    id: "psalm-55-22",
    text: "Cast your burden on the LORD and he will sustain you. He will never allow the righteous to be moved.",
    reference: "Psalm 55:22",
    translation: "WEB",
    verseCount: 1,
    book: "Psalm",
  },
  {
    id: "psalm-62-5-7",
    text: "Rest in God alone, O my soul, for my hope comes from Him. He alone is my rock and my salvation; He is my fortress; I will not be shaken. My salvation and my honor rest on God, my strong rock; my refuge is in God.",
    reference: "Psalm 62:5-7",
    translation: "BSB",
    verseCount: 3,
    book: "Psalm",
  },
  {
    id: "psalm-63-1-2",
    text: "O God, my God, you, you do I seek: my heart thirsts for you, my body faints for you in a parched and waterless land. As I in the temple have seen you, beholding your power and your glory,",
    reference: "Psalm 63:1-2",
    translation: "OEB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-71-5-6",
    text: "For You are my hope, O Lord GOD, my confidence from my youth. I have leaned on You since birth; You pulled me from my mother’s womb. My praise is always for You.",
    reference: "Psalm 71:5-6",
    translation: "BSB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-73-25-26",
    text: "Whom have I in the heavens but you? And on earth there is none I desire beside you. Though flesh and heart waste away, yet God is the rock of my heart, yet God is my portion forever.",
    reference: "Psalm 73:25-26",
    translation: "OEB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-84-10",
    text: "For a day in thy courts is better than a thousand. I had rather stand at the threshold of the house of my God, than dwell in the tents of wickedness.",
    reference: "Psalm 84:10",
    translation: "DARBY",
    verseCount: 1,
    book: "Psalm",
  },
  {
    id: "psalm-90-12",
    text: "So teach us to count our days, that we may gain a heart of wisdom.",
    reference: "Psalm 90:12",
    translation: "WEB",
    verseCount: 1,
    book: "Psalm",
  },
  {
    id: "psalm-103-8-10",
    text: "Jehovah is merciful and gracious, Slow to anger, and abundant in lovingkindness. He will not always chide; Neither will he keep his anger for ever. He hath not dealt with us after our sins, Nor rewarded us after our iniquities.",
    reference: "Psalm 103:8-10",
    translation: "ASV",
    verseCount: 3,
    book: "Psalm",
  },
  {
    id: "psalm-119-9-11",
    text: "Wherewith shall a young man cleanse his way? By taking heed thereto according to thy word. With my whole heart have I sought thee: Oh let me not wander from thy commandments. Thy word have I laid up in my heart, That I might not sin against thee.",
    reference: "Psalm 119:9-11",
    translation: "ASV",
    verseCount: 3,
    book: "Psalm",
  },
  {
    id: "psalm-121-1-2",
    text: "I will lift up my eyes to the hills. Where does my help come from? My help comes from the LORD, who made heaven and earth.",
    reference: "Psalm 121:1-2",
    translation: "WEB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-130-5-6",
    text: "I wait for the LORD. My soul waits. I hope in his word. My soul longs for the Lord more than watchmen long for the morning, more than watchmen for the morning.",
    reference: "Psalm 130:5-6",
    translation: "WEB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-139-23-24",
    text: "Search me, O God, and know my heart: Try me, and know my thoughts; And see if there be any wicked way in me, And lead me in the way everlasting.",
    reference: "Psalm 139:23-24",
    translation: "ASV",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "psalm-145-8-9",
    text: "The Lord is full of grace and pity, patient and rich in loving-kindness. The Lord is good to all the world, and his pity is over all things that he made.",
    reference: "Psalm 145:8-9",
    translation: "OEB",
    verseCount: 2,
    book: "Psalm",
  },
  {
    id: "proverbs-3-5-6",
    text: "Trust in the LORD with all your heart, and don’t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.",
    reference: "Proverbs 3:5-6",
    translation: "WEB",
    verseCount: 2,
    book: "Proverbs",
  },
  {
    id: "proverbs-3-13-14",
    text: "Blessed is the man who finds wisdom, the man who acquires understanding, for she is more profitable than silver, and her gain is better than fine gold.",
    reference: "Proverbs 3:13-14",
    translation: "BSB",
    verseCount: 2,
    book: "Proverbs",
  },
  {
    id: "proverbs-4-20-22",
    text: "My son, pay attention to my words; incline your ear to my sayings. Do not lose sight of them; keep them within your heart. For they are life to those who find them, and health to the whole body.",
    reference: "Proverbs 4:20-22",
    translation: "BSB",
    verseCount: 3,
    book: "Proverbs",
  },
  {
    id: "proverbs-10-12",
    text: "Hatred stirs up strife, but love covers all wrongs.",
    reference: "Proverbs 10:12",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-11-2",
    text: "When pride comes, then comes shame, but with humility comes wisdom.",
    reference: "Proverbs 11:2",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-12-18",
    text: "Speaking rashly is like a piercing sword, but the tongue of the wise brings healing.",
    reference: "Proverbs 12:18",
    translation: "BSB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-12-25",
    text: "Anxiety weighs down the heart of a man, but a good word cheers it up.",
    reference: "Proverbs 12:25",
    translation: "BSB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-13-20",
    text: "One who walks with wise men grows wise, but a companion of fools suffers harm.",
    reference: "Proverbs 13:20",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-14-29",
    text: "He that is slow to anger is of great understanding; But he that is hasty of spirit exalteth folly.",
    reference: "Proverbs 14:29",
    translation: "ASV",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-15-1",
    text: "A gentle answer turns away wrath, but a harsh word stirs up anger.",
    reference: "Proverbs 15:1",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-15-22",
    text: "Where there is no counsel, purposes are disappointed; But in the multitude of counsellors they are established.",
    reference: "Proverbs 15:22",
    translation: "ASV",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-16-9",
    text: "A man’s heart plans his course, but the LORD directs his steps.",
    reference: "Proverbs 16:9",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-16-18",
    text: "Pride goes before destruction, and an arrogant spirit before a fall.",
    reference: "Proverbs 16:18",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-17-17",
    text: "A friend loves at all times; and a brother is born for adversity.",
    reference: "Proverbs 17:17",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-18-13",
    text: "He who answers a matter before he hears it— this is folly and disgrace to him.",
    reference: "Proverbs 18:13",
    translation: "BSB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-19-17",
    text: "Kindness to the poor is a loan to the LORD, and He will repay the lender.",
    reference: "Proverbs 19:17",
    translation: "BSB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-20-22",
    text: "Don’t say, “I will pay back evil.” Wait for the LORD, and he will save you.",
    reference: "Proverbs 20:22",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-21-3",
    text: "To do righteousness and justice is more acceptable to the LORD than sacrifice.",
    reference: "Proverbs 21:3",
    translation: "WEB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "proverbs-22-9",
    text: "A generous man will be blessed, for he shares his bread with the poor.",
    reference: "Proverbs 22:9",
    translation: "BSB",
    verseCount: 1,
    book: "Proverbs",
  },
  {
    id: "ecclesiastes-3-11",
    text: "He has made everything beautiful in its time. He has also set eternity in the hearts of men, yet they cannot fathom the work that God has done from beginning to end.",
    reference: "Ecclesiastes 3:11",
    translation: "BSB",
    verseCount: 1,
    book: "Ecclesiastes",
  },
  {
    id: "ecclesiastes-4-9-10",
    text: "Two are better than one, because they have a good reward for their labor. For if they fall, the one will lift up his fellow; but woe to him who is alone when he falls, and doesn’t have another to lift him up.",
    reference: "Ecclesiastes 4:9-10",
    translation: "WEB",
    verseCount: 2,
    book: "Ecclesiastes",
  },
  {
    id: "ecclesiastes-5-2",
    text: "Don’t be rash with your mouth, and don’t let your heart be hasty to utter anything before God; for God is in heaven, and you on earth. Therefore let your words be few.",
    reference: "Ecclesiastes 5:2",
    translation: "WEB",
    verseCount: 1,
    book: "Ecclesiastes",
  },
  {
    id: "ecclesiastes-7-8-9",
    text: "Better is the end of a thing than its beginning. The patient in spirit is better than the proud in spirit. Don’t be hasty in your spirit to be angry, for anger rests in the bosom of fools.",
    reference: "Ecclesiastes 7:8-9",
    translation: "WEB",
    verseCount: 2,
    book: "Ecclesiastes",
  },
  {
    id: "ecclesiastes-7-20",
    text: "Surely there is not a righteous man on earth who does good and doesn’t sin.",
    reference: "Ecclesiastes 7:20",
    translation: "WEB",
    verseCount: 1,
    book: "Ecclesiastes",
  },
  {
    id: "ecclesiastes-9-10",
    text: "Whatsoever thy hand findeth to do, do it with thy might; for there is no work, nor device, nor knowledge, nor wisdom, in Sheol, whither thou goest.",
    reference: "Ecclesiastes 9:10",
    translation: "ASV",
    verseCount: 1,
    book: "Ecclesiastes",
  },
  {
    id: "ecclesiastes-12-13",
    text: "This is the end of the matter. All has been heard. Fear God and keep his commandments; for this is the whole duty of man.",
    reference: "Ecclesiastes 12:13",
    translation: "WEB",
    verseCount: 1,
    book: "Ecclesiastes",
  },
  {
    id: "song-of-solomon-2-10-11",
    text: "My beloved spoke, and said to me, “Rise up, my love, my beautiful one, and come away. For behold, the winter is past. The rain is over and gone.",
    reference: "Song of Solomon 2:10-11",
    translation: "WEB",
    verseCount: 2,
    book: "Song of Solomon",
  },
  {
    id: "song-of-solomon-4-7",
    text: "Thou art all fair, my love; And there is no spot in thee.",
    reference: "Song of Solomon 4:7",
    translation: "ASV",
    verseCount: 1,
    book: "Song of Solomon",
  },
  {
    id: "song-of-solomon-8-6",
    text: "Set me as a seal upon thy heart, As a seal upon thine arm: For love is strong as death; Jealousy is cruel as Sheol; The flashes thereof are flashes of fire, A very flame of Jehovah.",
    reference: "Song of Solomon 8:6",
    translation: "ASV",
    verseCount: 1,
    book: "Song of Solomon",
  },
  {
    id: "isaiah-6-8",
    text: "And I heard the voice of the Lord, saying: Whom shall I send? and who shall go for us? And I said: Lo, here am I, send me.",
    reference: "Isaiah 6:8",
    translation: "DRA",
    verseCount: 1,
    book: "Isaiah",
  },
  {
    id: "isaiah-26-3-4",
    text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee; because he trusteth in thee. Trust ye in Jehovah for ever; for in Jehovah, even Jehovah, is an everlasting rock.",
    reference: "Isaiah 26:3-4",
    translation: "ASV",
    verseCount: 2,
    book: "Isaiah",
  },
  {
    id: "isaiah-40-29",
    text: "He gives power to the weak. He increases the strength of him who has no might.",
    reference: "Isaiah 40:29",
    translation: "WEB",
    verseCount: 1,
    book: "Isaiah",
  },
  {
    id: "isaiah-58-6",
    text: "Isn’t this the fast that I have chosen: to break the chains of wickedness, to untie the cords of the yoke, to set the oppressed free and tear off every yoke?",
    reference: "Isaiah 58:6",
    translation: "BSB",
    verseCount: 1,
    book: "Isaiah",
  },
  {
    id: "jeremiah-6-16",
    text: "This is what the LORD says: “Stand at the crossroads and look. Ask for the ancient paths: ‘Where is the good way?’ Then walk in it, and you will find rest for your souls. But they said, ‘We will not walk in it!’",
    reference: "Jeremiah 6:16",
    translation: "BSB",
    verseCount: 1,
    book: "Jeremiah",
  },
  {
    id: "jeremiah-17-7",
    text: "“Blessed is the man who trusts in the LORD, and whose confidence is in the LORD.",
    reference: "Jeremiah 17:7",
    translation: "WEB",
    verseCount: 1,
    book: "Jeremiah",
  },
  {
    id: "lamentations-3-22-24",
    text: "It is because of the LORD’s loving kindnesses that we are not consumed, because his mercies don’t fail. They are new every morning. Great is your faithfulness. “The LORD is my portion,” says my soul. “Therefore I will hope in him.”",
    reference: "Lamentations 3:22-24",
    translation: "WEB",
    verseCount: 3,
    book: "Lamentations",
  },
  {
    id: "lamentations-3-25-26",
    text: "Jehovah is good unto them that wait for him, to the soul that seeketh him. It is good that a man should hope and quietly wait for the salvation of Jehovah.",
    reference: "Lamentations 3:25-26",
    translation: "ASV",
    verseCount: 2,
    book: "Lamentations",
  },
  {
    id: "ezekiel-36-26",
    text: "I will also give you a new heart, and I will put a new spirit within you. I will take away the stony heart out of your flesh, and I will give you a heart of flesh.",
    reference: "Ezekiel 36:26",
    translation: "WEB",
    verseCount: 1,
    book: "Ezekiel",
  },
  {
    id: "daniel-2-20-21",
    text: "Daniel answered, “Blessed be the name of God forever and ever; for wisdom and might are his. He changes the times and the seasons. He removes kings and sets up kings. He gives wisdom to the wise, and knowledge to those who have understanding.",
    reference: "Daniel 2:20-21",
    translation: "WEB",
    verseCount: 2,
    book: "Daniel",
  },
  {
    id: "hosea-6-6",
    text: "For I desire mercy, not sacrifice, and the knowledge of God rather than burnt offerings.",
    reference: "Hosea 6:6",
    translation: "BSB",
    verseCount: 1,
    book: "Hosea",
  },
  {
    id: "joel-2-12",
    text: "“Yet even now,” says the LORD, “turn to me with all your heart, and with fasting, and with weeping, and with mourning.”",
    reference: "Joel 2:12",
    translation: "WEB",
    verseCount: 1,
    book: "Joel",
  },
  {
    id: "amos-5-14-15",
    text: "Seek good, not evil, so that you may live. And the LORD, the God of Hosts, will be with you, as you have claimed. Hate evil and love good; establish justice in the gate. Perhaps the LORD, the God of Hosts, will be gracious to the remnant of Joseph.”",
    reference: "Amos 5:14-15",
    translation: "BSB",
    verseCount: 2,
    book: "Amos",
  },
  {
    id: "micah-6-8",
    text: "The Lord has told you what is good, what he demands of you: Only to do justice and love mercy, and to walk humbly with your God.",
    reference: "Micah 6:8",
    translation: "OEB",
    verseCount: 1,
    book: "Micah",
  },
  {
    id: "nahum-1-7",
    text: "The LORD is good, a stronghold in the day of trouble; and he knows those who take refuge in him.",
    reference: "Nahum 1:7",
    translation: "WEB",
    verseCount: 1,
    book: "Nahum",
  },
  {
    id: "habakkuk-2-4",
    text: "Behold, his soul is puffed up, it is not upright in him; but the righteous shall live by his faith.",
    reference: "Habakkuk 2:4",
    translation: "ASV",
    verseCount: 1,
    book: "Habakkuk",
  },
  {
    id: "haggai-1-5",
    text: "Now this is what the LORD of Hosts says: “Consider carefully your ways.",
    reference: "Haggai 1:5",
    translation: "BSB",
    verseCount: 1,
    book: "Haggai",
  },
  {
    id: "malachi-3-16",
    text: "At that time those who feared the LORD spoke with one another, and the LORD listened and heard them. So a scroll of remembrance was written before Him regarding those who feared the LORD and honored His name.",
    reference: "Malachi 3:16",
    translation: "BSB",
    verseCount: 1,
    book: "Malachi",
  },

  // The Gospels and Acts
  {
    id: "matthew-5-3-4",
    text: "“Blessed are the poor in spirit, for theirs is the Kingdom of Heaven. Blessed are those who mourn, for they shall be comforted.",
    reference: "Matthew 5:3-4",
    translation: "WEB",
    verseCount: 2,
    book: "Matthew",
  },
  {
    id: "matthew-5-7-9",
    text: "Blessed are the merciful, for they will find mercy. Blessed are the pure in heart, for they will see God. Blessed are the peacemakers, for they will be called children of God.",
    reference: "Matthew 5:7-9",
    translation: "OEB",
    verseCount: 3,
    book: "Matthew",
  },
  {
    id: "matthew-5-14-15",
    text: "Ye are the light of the world. A city set on a hill cannot be hid. Neither do men light a lamp, and put it under the bushel, but on the stand; and it shineth unto all that are in the house.",
    reference: "Matthew 5:14-15",
    translation: "ASV",
    verseCount: 2,
    book: "Matthew",
  },
  {
    id: "matthew-5-23-24",
    text: "Therefore, when presenting your gift at the altar, if even there you remember that your brother or sister has something against you, leave your gift there, before the altar, go and be reconciled to them, first, then come and present your gift.",
    reference: "Matthew 5:23-24",
    translation: "OEB",
    verseCount: 2,
    book: "Matthew",
  },
  {
    id: "matthew-5-41-42",
    text: "If you are forced to carry a soldier’s pack for one mile, carry it two. Give to anyone who asks and, if someone wants to borrow from you, do not turn them away.",
    reference: "Matthew 5:41-42",
    translation: "OEB",
    verseCount: 2,
    book: "Matthew",
  },
  {
    id: "matthew-6-6",
    text: "But you, when you pray, enter into your inner room, and having shut your door, pray to your Father who is in secret; and your Father who sees in secret will reward you openly.",
    reference: "Matthew 6:6",
    translation: "WEB",
    verseCount: 1,
    book: "Matthew",
  },
  {
    id: "matthew-6-31-32",
    text: "Do not then ask anxiously ‘What can we get to eat?’ or ‘What can we get to drink?’ or ‘What can we get to wear?’ All these are the things for which the nations are seeking, and your heavenly Father knows that you need them all.",
    reference: "Matthew 6:31-32",
    translation: "OEB",
    verseCount: 2,
    book: "Matthew",
  },
  {
    id: "matthew-7-12",
    text: "In everything, then, do to others as you would have them do to you. For this is the essence of the Law and the Prophets.",
    reference: "Matthew 7:12",
    translation: "BSB",
    verseCount: 1,
    book: "Matthew",
  },
  {
    id: "matthew-11-28-30",
    text: "Come unto me, all ye that labor and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light.",
    reference: "Matthew 11:28-30",
    translation: "ASV",
    verseCount: 3,
    book: "Matthew",
  },
  {
    id: "matthew-18-21-22",
    text: "Then Peter came to Jesus and asked, “Lord, how many times shall I forgive my brother who sins against me? Up to seven times?” Jesus answered, “I tell you, not just seven times, but seventy-seven times!",
    reference: "Matthew 18:21-22",
    translation: "BSB",
    verseCount: 2,
    book: "Matthew",
  },
  {
    id: "matthew-20-26",
    text: "It shall not be this way among you. Instead, whoever wants to become great among you must be your servant,",
    reference: "Matthew 20:26",
    translation: "BSB",
    verseCount: 1,
    book: "Matthew",
  },
  {
    id: "matthew-22-37-39",
    text: "Jesus declared, “‘Love the Lord your God with all your heart and with all your soul and with all your mind.’ This is the first and greatest commandment. And the second is like it: ‘Love your neighbor as yourself.’",
    reference: "Matthew 22:37-39",
    translation: "BSB",
    verseCount: 3,
    book: "Matthew",
  },
  {
    id: "matthew-28-18",
    text: "And having come near, Jesus spake to them, saying, 'Given to me was all authority in heaven and on earth;",
    reference: "Matthew 28:18",
    translation: "YLT",
    verseCount: 1,
    book: "Matthew",
  },
  {
    id: "mark-1-14-15",
    text: "After John had been arrested, Jesus went to Galilee, proclaiming the good news of God – “The time has come, and the kingdom of God is at hand; repent, and believe the good news.”",
    reference: "Mark 1:14-15",
    translation: "OEB",
    verseCount: 2,
    book: "Mark",
  },
  {
    id: "mark-2-27-28",
    text: "He said to them, “The Sabbath was made for man, not man for the Sabbath. Therefore the Son of Man is lord even of the Sabbath.”",
    reference: "Mark 2:27-28",
    translation: "WEB",
    verseCount: 2,
    book: "Mark",
  },
  {
    id: "mark-8-34",
    text: "Calling the people and his disciples to him, Jesus said, “If anyone wishes to walk in my steps, they must renounce self, take up their cross, and follow me.",
    reference: "Mark 8:34",
    translation: "OEB",
    verseCount: 1,
    book: "Mark",
  },
  {
    id: "mark-9-35",
    text: "Sitting down, Jesus called the Twelve and said, “If anyone wants to be first, he must be the last of all and the servant of all.”",
    reference: "Mark 9:35",
    translation: "BSB",
    verseCount: 1,
    book: "Mark",
  },
  {
    id: "mark-9-50",
    text: "Salt is good: but if the salt have lost its saltness, wherewith will ye season it? Have salt in yourselves, and be at peace one with another.",
    reference: "Mark 9:50",
    translation: "ASV",
    verseCount: 1,
    book: "Mark",
  },
  {
    id: "mark-10-14",
    text: "When, however, Jesus saw this, he was indignant. “Let the little children come to me,” he said, “do not hinder them; for it is to the childlike that the kingdom of God belongs.",
    reference: "Mark 10:14",
    translation: "OEB",
    verseCount: 1,
    book: "Mark",
  },
  {
    id: "mark-10-43-44",
    text: "But among you it is not so. No, whoever wants to become great among you must be your servant, and whoever wants to take the first place among you must be the servant of all;",
    reference: "Mark 10:43-44",
    translation: "OEB",
    verseCount: 2,
    book: "Mark",
  },
  {
    id: "mark-12-29-30",
    text: "Jesus answered, The first is, Hear, O Israel; The Lord our God, the Lord is one: and thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength.",
    reference: "Mark 12:29-30",
    translation: "ASV",
    verseCount: 2,
    book: "Mark",
  },
  {
    id: "luke-5-31-32",
    text: "Jesus answered, “It is not the healthy who need a doctor, but the sick. I have not come to call the righteous, but sinners, to repentance.”",
    reference: "Luke 5:31-32",
    translation: "BSB",
    verseCount: 2,
    book: "Luke",
  },
  {
    id: "luke-6-31",
    text: "Do to others as you would have them do to you.",
    reference: "Luke 6:31",
    translation: "BSB",
    verseCount: 1,
    book: "Luke",
  },
  {
    id: "luke-6-37",
    text: "Don’t judge, and you won’t be judged. Don’t condemn, and you won’t be condemned. Set free, and you will be set free.",
    reference: "Luke 6:37",
    translation: "WEB",
    verseCount: 1,
    book: "Luke",
  },
  {
    id: "luke-7-47-48",
    text: "Therefore I tell you, her sins, which are many, are forgiven, for she loved much. But one to whom little is forgiven, loves little.” He said to her, “Your sins are forgiven.”",
    reference: "Luke 7:47-48",
    translation: "WEB",
    verseCount: 2,
    book: "Luke",
  },
  {
    id: "luke-9-23-24",
    text: "Then Jesus said to all of them, “If anyone wants to come after Me, he must deny himself and take up his cross daily and follow Me. For whoever wants to save his life will lose it, but whoever loses his life for My sake will save it.",
    reference: "Luke 9:23-24",
    translation: "BSB",
    verseCount: 2,
    book: "Luke",
  },
  {
    id: "luke-10-27-28",
    text: "His reply was – “You must love the Lord your God with all your heart, and with all your soul, and with all your strength, and with all your mind; and your neighbor as you love yourself.” “You have answered right,” said Jesus, “Do that, and you will live.”",
    reference: "Luke 10:27-28",
    translation: "OEB",
    verseCount: 2,
    book: "Luke",
  },
  {
    id: "luke-10-36-37",
    text: "Now which, do you think, of these three men,” asked Jesus, “proved himself a neighbor to the man who fell into the robbers’ hands?” “The one that took pity on him,” was the answer; at which Jesus said, “Go and do the same yourself.”",
    reference: "Luke 10:36-37",
    translation: "OEB",
    verseCount: 2,
    book: "Luke",
  },
  {
    id: "luke-10-41-42",
    text: "But the Lord answered and said unto her, Martha, Martha, thou art anxious and troubled about many things: but one thing is needful: for Mary hath chosen the good part, which shall not be taken away from her.",
    reference: "Luke 10:41-42",
    translation: "ASV",
    verseCount: 2,
    book: "Luke",
  },
  {
    id: "luke-12-22-23",
    text: "He said to his disciples, “Therefore I tell you, don’t be anxious for your life, what you will eat, nor yet for your body, what you will wear. Life is more than food, and the body is more than clothing.",
    reference: "Luke 12:22-23",
    translation: "WEB",
    verseCount: 2,
    book: "Luke",
  },
  {
    id: "luke-12-33-34",
    text: "“Sell what belongs to you, and give in charity. Make yourselves purses that will not wear out – an inexhaustible treasure in heaven, where no thief comes near, or moth works ruin. For where your treasure is, there also will your heart be.",
    reference: "Luke 12:33-34",
    translation: "OEB",
    verseCount: 2,
    book: "Luke",
  },
  {
    id: "luke-18-13",
    text: "But the tax collector, standing far away, wouldn’t even lift up his eyes to heaven, but beat his chest, saying, ‘God, be merciful to me, a sinner!’",
    reference: "Luke 18:13",
    translation: "WEB",
    verseCount: 1,
    book: "Luke",
  },
  {
    id: "luke-19-8",
    text: "And Zacchæus stood, and said unto the Lord, Behold, Lord, the half of my goods I give to the poor; and if I have wrongfully exacted aught of any man, I restore fourfold.",
    reference: "Luke 19:8",
    translation: "ASV",
    verseCount: 1,
    book: "Luke",
  },
  {
    id: "luke-22-26",
    text: "But with you it must not be so. No, let the greatest among you become like the youngest, and him who leads like him who serves.",
    reference: "Luke 22:26",
    translation: "OEB",
    verseCount: 1,
    book: "Luke",
  },
  {
    id: "luke-24-5",
    text: "But, when in their fear the women bowed their faces to the ground, the men said to them, “Why are you looking among the dead for him who is living?",
    reference: "Luke 24:5",
    translation: "OEB",
    verseCount: 1,
    book: "Luke",
  },
  {
    id: "john-1-1-4",
    text: "In the beginning was the Word, and the Word was with God, and the Word was God. The same was in the beginning with God. All things were made through him. Without him, nothing was made that has been made. In him was life, and the life was the light of men.",
    reference: "John 1:1-4",
    translation: "WEB",
    verseCount: 4,
    book: "John",
  },
  {
    id: "john-1-14",
    text: "And the Word became flesh, and dwelt among us (and we beheld his glory, glory as of the only begotten from the Father), full of grace and truth.",
    reference: "John 1:14",
    translation: "ASV",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-3-16-17",
    text: "For God so loved the world that He gave His one and only Son, that everyone who believes in Him shall not perish but have eternal life. For God did not send His Son into the world to condemn the world, but to save the world through Him.",
    reference: "John 3:16-17",
    translation: "BSB",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-4-23-24",
    text: "But the hour comes, and now is, when the true worshipers will worship the Father in spirit and truth, for the Father seeks such to be his worshipers. God is spirit, and those who worship him must worship in spirit and truth.”",
    reference: "John 4:23-24",
    translation: "WEB",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-6-35",
    text: "Jesus answered, “I am the bread of life. Whoever comes to Me will never hunger, and whoever believes in Me will never thirst.",
    reference: "John 6:35",
    translation: "BSB",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-8-12",
    text: "Again, therefore, Jesus spoke to them, saying, “I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life.”",
    reference: "John 8:12",
    translation: "WEB",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-8-31-32",
    text: "Jesus therefore said to those Jews who had believed him, “If you remain in my word, then you are truly my disciples. You will know the truth, and the truth will make you free.”",
    reference: "John 8:31-32",
    translation: "WEB",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-10-10",
    text: "The thief comes only to steal, to kill, and to destroy; I have come so that they may have life, and may have it in greater fullness.",
    reference: "John 10:10",
    translation: "OEB",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-10-14-15",
    text: "I am the good shepherd. I know my own, and I’m known by my own; even as the Father knows me, and I know the Father. I lay down my life for the sheep.",
    reference: "John 10:14-15",
    translation: "WEB",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-11-25-26",
    text: "Jesus said unto her, I am the resurrection, and the life: he that believeth on me, though he die, yet shall he live; and whosoever liveth and believeth on me shall never die. Believest thou this?",
    reference: "John 11:25-26",
    translation: "ASV",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-12-24-25",
    text: "Verily, verily, I say unto you, Except the grain of wheat falling into the ground die, it abides alone; but if it die, it bears much fruit. He that loves his life shall lose it, and he that hates his life in this world shall keep it to life eternal.",
    reference: "John 12:24-25",
    translation: "DARBY",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-12-35",
    text: "Jesus therefore said unto them, Yet a little while is the light among you. Walk while ye have the light, that darkness overtake you not: and he that walketh in the darkness knoweth not whither he goeth.",
    reference: "John 12:35",
    translation: "ASV",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-13-14-15",
    text: "So if I, your Lord and Teacher, have washed your feet, you also should wash one another’s feet. I have set you an example so that you should do as I have done for you.",
    reference: "John 13:14-15",
    translation: "BSB",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-13-34-35",
    text: "I give you a new commandment – love one another; love one another as I have loved you. It is by this that everyone will recognize you as my disciples – by your loving one another.”",
    reference: "John 13:34-35",
    translation: "OEB",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-14-1-2",
    text: "Let not your heart be troubled: believe in God, believe also in me. In my Father’s house are many mansions; if it were not so, I would have told you; for I go to prepare a place for you.",
    reference: "John 14:1-2",
    translation: "ASV",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-14-6",
    text: "Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father, except through me.",
    reference: "John 14:6",
    translation: "WEB",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-14-15",
    text: "If you love me, you will lay my commands to heart,",
    reference: "John 14:15",
    translation: "OEB",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-14-25-26",
    text: "I have told you all this while still with you, but the helper – the Holy Spirit whom the Father will send in my name – will teach you all things, and will recall to your minds all that I have said to you.",
    reference: "John 14:25-26",
    translation: "OEB",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-15-4",
    text: "Abide in me, and I in you. As the branch cannot bear fruit of itself, except it abide in the vine; so neither can ye, except ye abide in me.",
    reference: "John 15:4",
    translation: "ASV",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-15-9-10",
    text: "As the Father has loved me, I also have loved you: abide in my love. If ye shall keep my commandments, ye shall abide in my love, as I have kept my Father's commandments and abide in his love.",
    reference: "John 15:9-10",
    translation: "DARBY",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-16-32",
    text: "Behold, the time is coming, yes, and has now come, that you will be scattered, everyone to his own place, and you will leave me alone. Yet I am not alone, because the Father is with me.",
    reference: "John 16:32",
    translation: "WEB",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-17-20-21",
    text: "“Not for these only do I pray, but for those also who will believe in me through their word, that they may all be one; even as you, Father, are in me, and I in you, that they also may be one in us; that the world may believe that you sent me.",
    reference: "John 17:20-21",
    translation: "WEB",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-20-19",
    text: "It was the first day of the week, and that very evening, while the disciples were together with the doors locked for fear of the Jews, Jesus came and stood among them. “Peace be with you!” He said to them.",
    reference: "John 20:19",
    translation: "BSB",
    verseCount: 1,
    book: "John",
  },
  {
    id: "john-20-27-28",
    text: "Then saith he to Thomas, Reach hither thy finger, and see my hands; and reach hither thy hand, and put it into my side: and be not faithless, but believing. Thomas answered and said unto him, My Lord and my God.",
    reference: "John 20:27-28",
    translation: "ASV",
    verseCount: 2,
    book: "John",
  },
  {
    id: "john-21-15",
    text: "So when they had broken their fast, Jesus saith to Simon Peter, Simon, son of John, lovest thou me more than these? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my lambs.",
    reference: "John 21:15",
    translation: "ASV",
    verseCount: 1,
    book: "John",
  },
  {
    id: "acts-2-42-44",
    text: "They continued steadfastly in the apostles’ teaching and fellowship, in the breaking of bread, and prayer. Fear came on every soul, and many wonders and signs were done through the apostles. All who believed were together, and had all things in common.",
    reference: "Acts 2:42-44",
    translation: "WEB",
    verseCount: 3,
    book: "Acts",
  },
  {
    id: "acts-4-32",
    text: "The whole body of those who had become believers in Christ were of one heart and mind. Not one of them claimed any of his goods as his own, but everything was held for the common use.",
    reference: "Acts 4:32",
    translation: "OEB",
    verseCount: 1,
    book: "Acts",
  },
  {
    id: "acts-10-34-35",
    text: "Then Peter began. “I see, beyond all doubt,” he said, “that God does not show partiality, but that in every nation he who reverences him and does what is right is acceptable to him.",
    reference: "Acts 10:34-35",
    translation: "OEB",
    verseCount: 2,
    book: "Acts",
  },
  {
    id: "acts-13-2-3",
    text: "While they were worshiping the Lord and fasting, the Holy Spirit said, “Set apart for Me Barnabas and Saul for the work to which I have called them.” And after they had fasted and prayed, they laid their hands on them and sent them off.",
    reference: "Acts 13:2-3",
    translation: "BSB",
    verseCount: 2,
    book: "Acts",
  },
  {
    id: "acts-16-25",
    text: "And at midnight Paul and Silas, in praying, were praising God with singing, and the prisoners listened to them.",
    reference: "Acts 16:25",
    translation: "DARBY",
    verseCount: 1,
    book: "Acts",
  },

  // The New Testament letters and Revelation
  {
    id: "romans-5-1-2",
    text: "Being therefore justified by faith, we have peace with God through our Lord Jesus Christ; through whom we also have our access by faith into this grace in which we stand. We rejoice in hope of the glory of God.",
    reference: "Romans 5:1-2",
    translation: "WEB",
    verseCount: 2,
    book: "Romans",
  },
  {
    id: "romans-8-1-2",
    text: "There is, therefore, now no condemnation for those who are in union with Christ Jesus; for through your union with Christ Jesus, the Law of the life-giving Spirit has set you free from the Law of sin and death.",
    reference: "Romans 8:1-2",
    translation: "OEB",
    verseCount: 2,
    book: "Romans",
  },
  {
    id: "romans-8-18-19",
    text: "I do not count the sufferings of our present life worthy of mention when compared with the glory that is to be revealed and bestowed on us. All nature awaits with eager expectation the appearing of the sons of God.",
    reference: "Romans 8:18-19",
    translation: "OEB",
    verseCount: 2,
    book: "Romans",
  },
  {
    id: "romans-8-26",
    text: "In the same way, the Spirit helps us in our weakness. For we do not know how we ought to pray, but the Spirit Himself intercedes for us with groans too deep for words.",
    reference: "Romans 8:26",
    translation: "BSB",
    verseCount: 1,
    book: "Romans",
  },
  {
    id: "romans-12-9",
    text: "Let your love be sincere. Hate the wrong; cling to the right.",
    reference: "Romans 12:9",
    translation: "OEB",
    verseCount: 1,
    book: "Romans",
  },
  {
    id: "romans-12-15-16",
    text: "Rejoice with those who rejoice; weep with those who weep. Live in harmony with one another. Do not be proud, but enjoy the company of the lowly. Do not be conceited.",
    reference: "Romans 12:15-16",
    translation: "BSB",
    verseCount: 2,
    book: "Romans",
  },
  {
    id: "romans-12-17-18",
    text: "Never return injury for injury. Aim at doing what everyone will recognize as honorable. If it is possible, as far as rests with you, live peaceably with everyone.",
    reference: "Romans 12:17-18",
    translation: "OEB",
    verseCount: 2,
    book: "Romans",
  },
  {
    id: "romans-13-8",
    text: "Owe no man anything, save to love one another: for he that loveth his neighbor hath fulfilled the law.",
    reference: "Romans 13:8",
    translation: "ASV",
    verseCount: 1,
    book: "Romans",
  },
  {
    id: "romans-14-18-19",
    text: "For whoever serves Christ in this way is pleasing to God and approved by men. So then, let us pursue what leads to peace and to mutual edification.",
    reference: "Romans 14:18-19",
    translation: "BSB",
    verseCount: 2,
    book: "Romans",
  },
  {
    id: "1-corinthians-4-1-2",
    text: "Let people look on us as Christ’s servants, and as stewards of the hidden truths of God. Now what we look for in stewards is that they should be trustworthy.",
    reference: "1 Corinthians 4:1-2",
    translation: "OEB",
    verseCount: 2,
    book: "1 Corinthians",
  },
  {
    id: "1-corinthians-10-23-24",
    text: "All things are lawful; but not all things are expedient. All things are lawful; but not all things edify. Let no man seek his own, but each his neighbor’s good.",
    reference: "1 Corinthians 10:23-24",
    translation: "ASV",
    verseCount: 2,
    book: "1 Corinthians",
  },
  {
    id: "1-corinthians-10-31",
    text: "So whether you eat or drink or whatever you do, do it all to the glory of God.",
    reference: "1 Corinthians 10:31",
    translation: "BSB",
    verseCount: 1,
    book: "1 Corinthians",
  },
  {
    id: "1-corinthians-12-4-6",
    text: "Gifts differ, but the Spirit is the same; ways of serving differ, yet the Master is the same; results differ, yet the God who brings about every result is in every case the same.",
    reference: "1 Corinthians 12:4-6",
    translation: "OEB",
    verseCount: 3,
    book: "1 Corinthians",
  },
  {
    id: "1-corinthians-13-13",
    text: "But now faith, hope, and love remain—these three. The greatest of these is love.",
    reference: "1 Corinthians 13:13",
    translation: "WEB",
    verseCount: 1,
    book: "1 Corinthians",
  },
  {
    id: "1-corinthians-15-58",
    text: "Wherefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labor is not vain in the Lord.",
    reference: "1 Corinthians 15:58",
    translation: "ASV",
    verseCount: 1,
    book: "1 Corinthians",
  },
  {
    id: "1-corinthians-16-13-14",
    text: "Watch! Stand firm in the faith! Be courageous! Be strong! Let all that you do be done in love.",
    reference: "1 Corinthians 16:13-14",
    translation: "WEB",
    verseCount: 2,
    book: "1 Corinthians",
  },
  {
    id: "2-corinthians-4-16",
    text: "Therefore we do not lose heart. Though our outer self is wasting away, yet our inner self is being renewed day by day.",
    reference: "2 Corinthians 4:16",
    translation: "BSB",
    verseCount: 1,
    book: "2 Corinthians",
  },
  {
    id: "2-corinthians-5-17",
    text: "Therefore if anyone is in Christ, he is a new creation. The old has passed away. Behold, the new has come!",
    reference: "2 Corinthians 5:17",
    translation: "BSB",
    verseCount: 1,
    book: "2 Corinthians",
  },
  {
    id: "2-corinthians-12-9",
    text: "And he hath said unto me, My grace is sufficient for thee: for my power is made perfect in weakness. Most gladly therefore will I rather glory in my weaknesses, that the power of Christ may rest upon me.",
    reference: "2 Corinthians 12:9",
    translation: "ASV",
    verseCount: 1,
    book: "2 Corinthians",
  },
  {
    id: "galatians-5-13-14",
    text: "For you, brothers, were called to freedom; but do not use your freedom as an opportunity for the flesh. Rather, serve one another in love. The entire law is fulfilled in a single decree: “Love your neighbor as yourself.”",
    reference: "Galatians 5:13-14",
    translation: "BSB",
    verseCount: 2,
    book: "Galatians",
  },
  {
    id: "galatians-5-22-23",
    text: "But the fruit produced by the Spirit is love, joy, peace, forbearance, kindliness, generosity, trustfulness, gentleness, self-control. Against such things there is no law!",
    reference: "Galatians 5:22-23",
    translation: "OEB",
    verseCount: 2,
    book: "Galatians",
  },
  {
    id: "galatians-6-1-2",
    text: "Brothers, even if a man is caught in some fault, you who are spiritual must restore such a one in a spirit of gentleness, looking to yourself so that you also aren’t tempted. Bear one another’s burdens, and so fulfill the law of Christ.",
    reference: "Galatians 6:1-2",
    translation: "WEB",
    verseCount: 2,
    book: "Galatians",
  },
  {
    id: "galatians-6-9-10",
    text: "Let us not grow weary in well-doing, for in due time we will reap a harvest if we do not give up. Therefore, as we have opportunity, let us do good to everyone, and especially to the family of faith.",
    reference: "Galatians 6:9-10",
    translation: "BSB",
    verseCount: 2,
    book: "Galatians",
  },
  {
    id: "ephesians-2-10",
    text: "For we are God’s workmanship, created in Christ Jesus to do good works, which God prepared in advance as our way of life.",
    reference: "Ephesians 2:10",
    translation: "BSB",
    verseCount: 1,
    book: "Ephesians",
  },
  {
    id: "ephesians-4-1-3",
    text: "I therefore, the prisoner in the Lord, beg you to walk worthily of the calling with which you were called, with all lowliness and humility, with patience, bearing with one another in love, being eager to keep the unity of the Spirit in the bond of peace.",
    reference: "Ephesians 4:1-3",
    translation: "WEB",
    verseCount: 3,
    book: "Ephesians",
  },
  {
    id: "ephesians-4-25-27",
    text: "Therefore each of you must put off falsehood and speak truthfully to his neighbor, for we are all members of one another. “Be angry, yet do not sin.” Do not let the sun set upon your anger, and do not give the devil a foothold.",
    reference: "Ephesians 4:25-27",
    translation: "BSB",
    verseCount: 3,
    book: "Ephesians",
  },
  {
    id: "ephesians-4-31-32",
    text: "Let all bitterness, passion, anger, brawling, and abusive language be banished from among you, as well as all malice. Be kind to one another, tenderhearted, ready to forgive one another, just as God, in Christ, forgave you.",
    reference: "Ephesians 4:31-32",
    translation: "OEB",
    verseCount: 2,
    book: "Ephesians",
  },
  {
    id: "ephesians-5-15-17",
    text: "Take great care, then, how you live – not unwisely but wisely, making the most of every opportunity; for these are evil days. Therefore do not grow thoughtless, but try to understand what the Lord’s will is.",
    reference: "Ephesians 5:15-17",
    translation: "OEB",
    verseCount: 3,
    book: "Ephesians",
  },
  {
    id: "philippians-4-6-7",
    text: "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.",
    reference: "Philippians 4:6-7",
    translation: "WEB",
    verseCount: 2,
    book: "Philippians",
  },
  {
    id: "philippians-4-9",
    text: "Whatever you have learned or received or heard from me, or seen in me, put it into practice. And the God of peace will be with you.",
    reference: "Philippians 4:9",
    translation: "BSB",
    verseCount: 1,
    book: "Philippians",
  },
  {
    id: "colossians-3-14",
    text: "And over all these virtues put on love, which is the bond of perfect unity.",
    reference: "Colossians 3:14",
    translation: "BSB",
    verseCount: 1,
    book: "Colossians",
  },
  {
    id: "colossians-3-15",
    text: "And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful.",
    reference: "Colossians 3:15",
    translation: "WEB",
    verseCount: 1,
    book: "Colossians",
  },
  {
    id: "colossians-3-23-24",
    text: "Whatever you do, do it with all your heart, as if working for the Master and not for people, since you know that it is from the Master that you will receive the inheritance which will be your reward. You are serving Christ, the Master.",
    reference: "Colossians 3:23-24",
    translation: "OEB",
    verseCount: 2,
    book: "Colossians",
  },
  {
    id: "colossians-4-5-6",
    text: "Show tact in your behavior to the outside world, making the most of every opportunity. Let your conversation always be kindly, but not bland, season it, as it were, with salt; be aware in each case of the answer you should be giving.",
    reference: "Colossians 4:5-6",
    translation: "OEB",
    verseCount: 2,
    book: "Colossians",
  },
  {
    id: "1-thessalonians-5-11",
    text: "Therefore encourage and build one another up, just as you are already doing.",
    reference: "1 Thessalonians 5:11",
    translation: "BSB",
    verseCount: 1,
    book: "1 Thessalonians",
  },
  {
    id: "1-thessalonians-5-14-15",
    text: "We exhort you, brothers: Admonish the disorderly; encourage the faint-hearted; support the weak; be patient toward all. See that no one returns evil for evil to anyone, but always follow after that which is good for one another and for all.",
    reference: "1 Thessalonians 5:14-15",
    translation: "WEB",
    verseCount: 2,
    book: "1 Thessalonians",
  },
  {
    id: "1-thessalonians-5-16-18",
    text: "Always be joyful; never cease to pray; under all circumstances give thanks to God. For this is his will for you as made known in Christ Jesus.",
    reference: "1 Thessalonians 5:16-18",
    translation: "OEB",
    verseCount: 3,
    book: "1 Thessalonians",
  },
  {
    id: "2-thessalonians-3-13",
    text: "But you, brothers, don’t be weary in doing what is right.",
    reference: "2 Thessalonians 3:13",
    translation: "WEB",
    verseCount: 1,
    book: "2 Thessalonians",
  },
  {
    id: "1-timothy-4-12",
    text: "Let no one despise your youth, but set an example for the believers in speech, in conduct, in love, in faith, in purity.",
    reference: "1 Timothy 4:12",
    translation: "BSB",
    verseCount: 1,
    book: "1 Timothy",
  },
  {
    id: "1-timothy-6-6-8",
    text: "But godliness with contentment is great gain. For we brought nothing into the world, and we certainly can’t carry anything out. But having food and clothing, we will be content with that.",
    reference: "1 Timothy 6:6-8",
    translation: "WEB",
    verseCount: 3,
    book: "1 Timothy",
  },
  {
    id: "2-timothy-1-7",
    text: "For the Spirit which God gave us was not a spirit of cowardice, but a spirit of power, love, and self-control.",
    reference: "2 Timothy 1:7",
    translation: "OEB",
    verseCount: 1,
    book: "2 Timothy",
  },
  {
    id: "2-timothy-2-1-2",
    text: "You therefore, my child, be strong in the grace that is in Christ Jesus. And the things that you have heard me say among many witnesses, entrust these to faithful men who will be qualified to teach others as well.",
    reference: "2 Timothy 2:1-2",
    translation: "BSB",
    verseCount: 2,
    book: "2 Timothy",
  },
  {
    id: "2-timothy-3-16-17",
    text: "Every Scripture is God-breathed and profitable for teaching, for reproof, for correction, and for instruction in righteousness, that each person who belongs to God may be complete, thoroughly equipped for every good work.",
    reference: "2 Timothy 3:16-17",
    translation: "WEB",
    verseCount: 2,
    book: "2 Timothy",
  },
  {
    id: "titus-3-1-2",
    text: "Remind them to respect and obey the rulers and authorities, to be ready for every kind of good work, to slander no one, to avoid quarreling, to be reasonable, and under all circumstances to show a gentle spirit with all.",
    reference: "Titus 3:1-2",
    translation: "OEB",
    verseCount: 2,
    book: "Titus",
  },
  {
    id: "hebrews-4-14",
    text: "Therefore, since we have a great high priest who has passed through the heavens, Jesus the Son of God, let us hold firmly to what we profess.",
    reference: "Hebrews 4:14",
    translation: "BSB",
    verseCount: 1,
    book: "Hebrews",
  },
  {
    id: "hebrews-6-10",
    text: "For God is not unjust. He will not forget your work and the love you have shown for His name as you have ministered to the saints and continue to do so.",
    reference: "Hebrews 6:10",
    translation: "BSB",
    verseCount: 1,
    book: "Hebrews",
  },
  {
    id: "hebrews-10-24-25",
    text: "Let us vie with one another in a rivalry of love and noble actions. And let us not, as some do, cease to meet together; but, on the contrary, let us encourage one another, and all the more, now that you see the day drawing near.",
    reference: "Hebrews 10:24-25",
    translation: "OEB",
    verseCount: 2,
    book: "Hebrews",
  },
  {
    id: "hebrews-11-1-2",
    text: "Now faith is the assurance of what we hope for and the certainty of what we do not see. This is why the ancients were commended.",
    reference: "Hebrews 11:1-2",
    translation: "BSB",
    verseCount: 2,
    book: "Hebrews",
  },
  {
    id: "hebrews-13-1-3",
    text: "Let brotherly love abide. Be not forgetful of hospitality; for by it some have unawares entertained angels. Remember prisoners, as bound with [them]; those that are evil-treated, as being yourselves also in [the] body.",
    reference: "Hebrews 13:1-3",
    translation: "DARBY",
    verseCount: 3,
    book: "Hebrews",
  },
  {
    id: "hebrews-13-15-16",
    text: "By him therefore let us offer the sacrifice of praise always to God, that is to say, the fruit of lips confessing to his name. And do not forget to do good, and to impart; for by such sacrifices God’s favour is obtained.",
    reference: "Hebrews 13:15-16",
    translation: "DRA",
    verseCount: 2,
    book: "Hebrews",
  },
  {
    id: "james-1-2-4",
    text: "Consider it pure joy, my brothers, when you encounter trials of many kinds, because you know that the testing of your faith develops perseverance. Allow perseverance to finish its work, so that you may be mature and complete, not lacking anything.",
    reference: "James 1:2-4",
    translation: "BSB",
    verseCount: 3,
    book: "James",
  },
  {
    id: "james-1-19-20",
    text: "So, then, my beloved brothers, let every man be swift to hear, slow to speak, and slow to anger; for the anger of man doesn’t produce the righteousness of God.",
    reference: "James 1:19-20",
    translation: "WEB",
    verseCount: 2,
    book: "James",
  },
  {
    id: "james-1-22",
    text: "Be doers of the word, and not hearers only. Otherwise, you are deceiving yourselves.",
    reference: "James 1:22",
    translation: "BSB",
    verseCount: 1,
    book: "James",
  },
  {
    id: "james-3-13-14",
    text: "Who among you claims to be wise and intelligent? They should show that their actions are the outcome of a good life lived in the humility of true wisdom. But if you harbor bitter envy and a spirit of rivalry in your hearts, do not boast or deny the truth.",
    reference: "James 3:13-14",
    translation: "OEB",
    verseCount: 2,
    book: "James",
  },
  {
    id: "james-4-6-7",
    text: "But he gives more grace. Wherefore he says, God sets himself against [the] proud, but gives grace to [the] lowly. Subject yourselves therefore to God. Resist the devil, and he will flee from you.",
    reference: "James 4:6-7",
    translation: "DARBY",
    verseCount: 2,
    book: "James",
  },
  {
    id: "james-5-19-20",
    text: "My brothers, if one of you should wander from the truth and someone should bring him back, consider this: Whoever turns a sinner from the error of his way will save his soul from death and cover over a multitude of sins.",
    reference: "James 5:19-20",
    translation: "BSB",
    verseCount: 2,
    book: "James",
  },
  {
    id: "1-peter-2-9",
    text: "But you are a chosen people, a royal priesthood, a holy nation, a people for God’s own possession, to proclaim the virtues of Him who called you out of darkness into His marvelous light.",
    reference: "1 Peter 2:9",
    translation: "BSB",
    verseCount: 1,
    book: "1 Peter",
  },
  {
    id: "1-peter-4-8-9",
    text: "Above all things, let your love for one another be earnest, for ‘Love throws a veil over countless sins.’ Never grudge hospitality to one another.",
    reference: "1 Peter 4:8-9",
    translation: "OEB",
    verseCount: 2,
    book: "1 Peter",
  },
  {
    id: "1-peter-5-5",
    text: "Again, you younger ones should show deference to the older. And all of you should put on the badge of humility in mutual service, for ‘God is opposed to the proud, but gives his help to the humble.’",
    reference: "1 Peter 5:5",
    translation: "OEB",
    verseCount: 1,
    book: "1 Peter",
  },
  {
    id: "2-peter-3-13-14",
    text: "But in keeping with God’s promise, we are looking forward to a new heaven and a new earth, where righteousness dwells. Therefore, beloved, as you anticipate these things, make every effort to be found at peace—spotless and blameless in His sight.",
    reference: "2 Peter 3:13-14",
    translation: "BSB",
    verseCount: 2,
    book: "2 Peter",
  },
  {
    id: "1-john-1-5-6",
    text: "This is the message which we have heard from him and announce to you: God is light, and there is no darkness in him at all. If we say that we have fellowship with him and yet continue to walk in the darkness, our words and our lives are a lie.",
    reference: "1 John 1:5-6",
    translation: "OEB",
    verseCount: 2,
    book: "1 John",
  },
  {
    id: "1-john-1-8-9",
    text: "If we say we have no sin, we deceive ourselves, and the truth is not in us. If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.",
    reference: "1 John 1:8-9",
    translation: "BSB",
    verseCount: 2,
    book: "1 John",
  },
  {
    id: "1-john-3-16",
    text: "By this we know what love is: Jesus laid down His life for us, and we ought to lay down our lives for our brothers.",
    reference: "1 John 3:16",
    translation: "BSB",
    verseCount: 1,
    book: "1 John",
  },
  {
    id: "1-john-4-7-8",
    text: "Beloved, let us love one another, because love comes from God. Everyone who loves has been born of God and knows God. Whoever does not love does not know God, because God is love.",
    reference: "1 John 4:7-8",
    translation: "BSB",
    verseCount: 2,
    book: "1 John",
  },
  {
    id: "1-john-4-18-19",
    text: "There is no fear in love; perfect love drives out fear because fear has to do with punishment. So anyone who is afraid has not reached perfection in love. We love, because God first loved us.",
    reference: "1 John 4:18-19",
    translation: "OEB",
    verseCount: 2,
    book: "1 John",
  },
  {
    id: "2-john-1-4",
    text: "It was a great joy to me to find the lives of some of your children guided by the truth, in obedience to the command that we received from the Father.",
    reference: "2 John 1:4",
    translation: "OEB",
    verseCount: 1,
    book: "2 John",
  },
  {
    id: "3-john-1-5",
    text: "Beloved, you are faithful in what you are doing for the brothers, and especially since they are strangers to you.",
    reference: "3 John 1:5",
    translation: "BSB",
    verseCount: 1,
    book: "3 John",
  },
  {
    id: "jude-1-20-21",
    text: "But you, beloved, keep building up yourselves on your most holy faith, praying in the Holy Spirit. Keep yourselves in God’s love, looking for the mercy of our Lord Jesus Christ to eternal life.",
    reference: "Jude 1:20-21",
    translation: "WEB",
    verseCount: 2,
    book: "Jude",
  },
  {
    id: "revelation-7-16-17",
    text: "They will never be hungry or thirsty any more. The sun won’t beat on them, nor any heat; for the Lamb who is in the middle of the throne shepherds them and leads them to springs of life-giving waters. And God will wipe away every tear from their eyes.”",
    reference: "Revelation 7:16-17",
    translation: "WEB",
    verseCount: 2,
    book: "Revelation",
  },
  {
    id: "revelation-21-3",
    text: "I heard a loud voice out of heaven saying, “Behold, God’s dwelling is with people; and he will dwell with them, and they will be his people, and God himself will be with them as their God.",
    reference: "Revelation 21:3",
    translation: "WEB",
    verseCount: 1,
    book: "Revelation",
  },
  {
    id: "revelation-21-5",
    text: "And the One seated on the throne said, “Behold, I make all things new.” Then He said, “Write this down, for these words are faithful and true.”",
    reference: "Revelation 21:5",
    translation: "BSB",
    verseCount: 1,
    book: "Revelation",
  },
  {
    id: "revelation-22-20",
    text: "He who testifies these things says, “Yes, I am coming soon.” Amen! Yes, come, Lord Jesus!",
    reference: "Revelation 22:20",
    translation: "WEB",
    verseCount: 1,
    book: "Revelation",
  },
  {
    id: "matthew-5-16",
    text: "Even so, let your light shine before men, that they may see your good works and glorify your Father who is in heaven.",
    reference: "Matthew 5:16",
    translation: "WEB",
    verseCount: 1,
    book: "Matthew",
  },
  {
    id: "matthew-9-13",
    text: "But you go and learn what this means: ‘I desire mercy, and not sacrifice,’ for I came not to call the righteous, but sinners to repentance.”",
    reference: "Matthew 9:13",
    translation: "WEB",
    verseCount: 1,
    book: "Matthew",
  },
  {
    id: "mark-5-19",
    text: "But Jesus would not allow him. “Go home to your own people,” He said, “and tell them how much the Lord has done for you, and what mercy He has shown you.”",
    reference: "Mark 5:19",
    translation: "BSB",
    verseCount: 1,
    book: "Mark",
  },
  {
    id: "mark-6-31-32",
    text: "He said to them, “Come away into a deserted place, and rest awhile.” For there were many coming and going, and they had no leisure so much as to eat. They went away in the boat to a deserted place by themselves.",
    reference: "Mark 6:31-32",
    translation: "WEB",
    verseCount: 2,
    book: "Mark",
  },
  {
    id: "luke-23-34",
    text: "And Jesus said: Father, forgive them, for they know not what they do. But they, dividing his garments, cast lots.",
    reference: "Luke 23:34",
    translation: "DRA",
    verseCount: 1,
    book: "Luke",
  },
  {
    id: "acts-20-35",
    text: "In all things I gave you an example, that so laboring you ought to help the weak, and to remember the words of the Lord Jesus, that he himself said, ‘It is more blessed to give than to receive.’ ”",
    reference: "Acts 20:35",
    translation: "WEB",
    verseCount: 1,
    book: "Acts",
  },
  {
    id: "romans-15-7",
    text: "Therefore accept one another, even as Christ also accepted you, to the glory of God.",
    reference: "Romans 15:7",
    translation: "WEB",
    verseCount: 1,
    book: "Romans",
  },
  {
    id: "ephesians-4-29",
    text: "Never let any foul word pass your lips, but only such good words as the occasion demands, so that they may be a help to those who hear them.",
    reference: "Ephesians 4:29",
    translation: "OEB",
    verseCount: 1,
    book: "Ephesians",
  },
  {
    id: "philippians-4-11",
    text: "I am not saying this out of need, for I have learned to be content regardless of my circumstances.",
    reference: "Philippians 4:11",
    translation: "BSB",
    verseCount: 1,
    book: "Philippians",
  },
  {
    id: "revelation-21-4",
    text: "He will wipe away every tear from their eyes. Death will be no more; neither will there be mourning, nor crying, nor pain any more. The first things have passed away.”",
    reference: "Revelation 21:4",
    translation: "WEB",
    verseCount: 1,
    book: "Revelation",
  },
] as const satisfies readonly BibleVerseMessage[];
